### ISSUE TITLE
Error running VCF Readcount Annotator

### ISSUE THREAD

**Issue by carolinamelo** [griffithlab/VAtools#13]
Hello!
I'm running the following command line: 

vcf-readcount-annotator mysample_vep_output.vcf mysample_bam_readcount DNA -s mysample

This returns the following error:

Traceback (most recent call last):
  File "/home/BIG/CMelo/miniconda3/envs/py35/bin/vcf-readcount-annotator", line 11, in <module>
    sys.exit(main())
  File "/home/BIG/CMelo/miniconda3/envs/py35/lib/python3.5/site-packages/vcf_annotation_tools/vcf_readcount_annotator.py", line 213, in main
    ads.append(brct[ref_base])
TypeError: 'NoneType' object is not subscriptable

I'm using different WGS samples and the output I get is truncated in different points for each one. Some stops on Chr 6 and other ones on Chr 1 but the error message is always the same. For few I've got the result for all Chromosomes with no errors. Any guess of what can it be?

**Comment by susannasiebert** [comment]
@carolinamelo would you mind attaching a sample VCF and bam readcount file that is causing this error so that I can reproduce it on my end? Also, what version of the vcf-annotation-tools package are you using?

**Comment by carolinamelo** [comment]
Hi @susannasiebert! Unfortunately my vcf file is too big to upload here... 27MB.
I've uploaded some txt files with the end of the annotator output and the respective parts from bam and vcf files used to generate them, for 2 different samples. One stops on the Chr 1 and the other one on the Chr 13. The version I'm using is the 1.4.4.

Of note, it works fine with my WES samples, but not with WGS samples. Also it does not have problem with the vcf expression annotator, either with WES or WGS samples. I wonder if it is something related with the fact that I merged 5 samples (replicates) before run the bam readcount. For WES samples I only had 2 of each to merge. I noticed that both cases I'm sending to you stopped before a line (position) where the PL had 6 numbers separated by comma (GT:PL   1/2:218,66,42,169,0,163). Maybe this is causing confusion when the software has to add the DP:AF:AD values. Does it make sense?

PS: My bam readcount file contains only snp data. I'm not considering indels.

[erro_readcount_annotator.zip](https://github.com/griffithlab/vcf-annotation-tools/files/2618171/erro_readcount_annotator.zip)


Thank you very much!

**Comment by carolinamelo** [comment]
Comparison with the expression annotator output:

[sample_011_expression_vs_readcount_annotator.txt](https://github.com/griffithlab/vcf-annotation-tools/files/2618263/sample_011_expression_vs_readcount_annotator.txt)

**Comment by carolinamelo** [comment]
Updating... From 30 WGS samples I've got success with one. So it doesn't seem to be nothing related with merge 5 samples or the PL with 6 numbers, as all this conditions are present in this sample . If is there any other way to send you the zipped vcf files, please let me know. Here, only 10 MB is allowed for upload.
Thank you!

**Comment by susannasiebert** [comment]
I have found the reason for this bug and will submit a pull request shortly.

**Comment by susannasiebert** [comment]
I made a new release (1.4.5) that includes the bugfix for this issues. Please update to the latest version and try it again. I'm resolving this for issue for now but please feel free to reopen if the issue persists after updating to the latest version.

**Comment by carolinamelo** [comment]
It worked fine!
Thank you very much!
