### ISSUE TITLE
Add a tool that can write R fields to a TSV in a decomposed manner

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/VAtools#20]
GATK VariantsToTable will not split out R-number fields while a user might only be interested in the alt value (e.g. for the allele read counts). We should make a tool that can take any arbitrary R-number field and write the values as `<FIELD>-REF` and `<FIELD>-ALT`. This will only work for decomposed variants.

**Comment by malachig** [comment]
Thinking out loud...

Something like transform-split-values?  Assumes you have a field with at least two values delimited by a comma.  Then you could add operations to subject these to (sum, ratio-of-a [e.g. ref VAF], ratio-of-b [e.g. alt VAF], min, max, etc.).  And allow the user to name the result.  e.g.

`transform-split-values --sample TUMOR --field AD --operation sum --field-name total_tumor_depth`

`transform-split-values --sample TUMOR --field AD --operation ratio-of-b --field-name tumor_VAF`
