### ISSUE TITLE
New feature to support writing VCF format meta-data headers to both VCF and TSV output files.

### ISSUE THREAD

**Issue by jasonwalker80** [griffithlab/VAtools#23]
It would be nice to add a common, optional input(s) to this toolkit to write provided key/value meta-data fields to the output VCF and TSV files. I would assume that if the key already exists, then the existing value would be overwritten. 

The VCF spec contains some information on what's acceptable for meta-data lines in the header. Most TSV readers and software such as Excel can be told to ignore or deal with pound commented lines, ex. `##`. The relevant VCF spec:

> 1.4 Meta-information lines
> File meta-information is included after the ## string and must be key=value pairs. Meta-information lines are optional, but if they are present then they must be completely well-formed. Note that BCF, the binary counterpart of VCF, requires that all entries are present. It is recommended to include meta-information lines describing the entries used in the body of the VCF file.
> All structured lines that have their value enclosed within ”<>” require an ID which must be unique within their type. For all of the structured lines (##INFO, ##FORMAT, ##FILTER, etc.), extra fields can be included after the default fields. For example:
> ##INFO=<ID=ID,Number=number,Type=type,Description="description",Source="description",Version="128">
> In the above example, the extra fields of “Source” and “Version” are provided. Optional fields must be stored as strings even for numeric values.
> It is recommended in VCF and required in BCF that the header includes tags describing the reference and contigs backing the data contained in the file. These tags are based on the SQ field from the SAM spec; all tags are optional (see the VCF example above).
> Meta-information lines can be in any order with the exception of ‘fileformat‘ which must come first.

**Comment by susannasiebert** [comment]
It's not quite clear to me how this information would be provided to the tool. I assume we would want to be able to write an arbitrary number of headers to the VCF but then each header has a set of key-value pairs. 

I almost wonder if it would just be easier to cat a header.txt before the .tsv files instead of having a tool do it. This depends on the all of the information we want to include and obviously wouldn't work for VCFs. @jasonwalker80 can you add an example of a specific use case?

**Comment by susannasiebert** [comment]
The header that Dave Spencer wants to appends looks like this:
```
Myeloseq Assay Version 1.0 -- This laboratory developed test (LDT) was developed and its performance characteristics determined by the CLIA Licensed Environment laboratory at the McDonnell Genome Institute at Washington University (MGI-CLE, CLIA #26D2092546, CAP #9047655), Dr. David H. Spencer MD, PhD, FCAP, Medical Director. 4444 Forest Park Avenue, Rm 4127 St. Louis, Missouri 63108 (314) 286-1460 Fax: (314) 286-1810. The MGI-CLE laboratory is regulated under CLIA as certified to perform high-complexity testing. This test has not been cleared or approved by the FDA.
```
Given that this is just a simple text string I would propose to save this text into a txt file on core disk and then using a `cat` step in our CWLs on that file and the VCF/TSV to concatinate them together. I don't think that VAtools is the right place for this.
