### ISSUE TITLE
vcf-expression annotator  "Expression entry"

### ISSUE THREAD

**Issue by nourelislam** [griffithlab/VAtools#28]
Dear All,
I am running vcf-expression annotator via this command
vcf-expression-annotator $VCF simple_gene_counts.txt custom gene --id-column Geneid --expression-column gerald_C1TD1ACXX_8_ACAGTG.sorted.bam -s H_NJ-HCC1395-HCC1395-GatkSomaticIndel

on vep-annotated vcf with the vep arguments as below:
vep -i ~/Documents/neoantigen/DNA_data/hcc1395.build135650880.exome.snvs.vcf -o hcc1395.build135650880.exome.snvs.ann.vcf --format vcf --vcf --symbol --terms SO /
--tsl --hgvs --fasta ~/Documents/neoantigen/DNA_data/GRCh37-lite.fa --offline --cache --plugin Downstream --plugin Wildtype --verbose

but the software gives this error:
WARNING:root:891352 of 891352 transcripts did not have an expression entry for their gene id

Please help

**Comment by susannasiebert** [comment]
This would occur when the entries in the `Geneid` column of your expression file don't match what is in the `Gene` annotation from VEP. Most likely the `Geneid` column doesn't contain gene names but some other sort of identifier. Without seeing your input files, it is difficult to tell exactly what might be going wrong.

**Comment by susannasiebert** [comment]
Correction to my previous statement. It looks like `Gene` column from VEP actually contains Ensembl gene ids so that is what the vcf-expression-annotator is looking for in the gene expression file.

**Comment by nourelislam** [comment]
Dear Ms. Susan,
Thanks for your response, I have checked my expression file, actually Gene-id column has the same ids which is found in the vep annotated file but not the version for example expression file contains ENSG00000227232.4. On the other hands, vep annotated vcf has only ENSG00000227232 without .4 version. Is that the case?
If this is the case I have tried to add --ignore transcript version argument in the vcf-expression annotator but it doesn't help
 I really appreciate your help

**Comment by susannasiebert** [comment]
I believe that the `--ignore-transcript-version` will only work if your VEP annotations include the transcript version, not the expression file. If you could attach your actual input files, I would be able to step through it in the debugger and confirm this.

**Comment by nourelislam** [comment]
@susannasiebert  
Here is the files:
[hcc1395.build135650880.exome.indels.ann.vcf.gz](https://github.com/griffithlab/VAtools/files/3560452/hcc1395.build135650880.exome.indels.ann.vcf.gz) 
[simple_gene_counts_two.txt](https://github.com/griffithlab/VAtools/files/3560469/simple_gene_counts_two.txt)

Thanks a lot for your kind help

**Comment by nourelislam** [comment]
Dear Ms. Susanna @susannasiebert 
Is there something wrong with my files?

Thanks

**Comment by susannasiebert** [comment]
There is nothing wrong with your files. The problem is that the `--ignore-transcript-version` doesn't work in gene mode. I will need to release a bugfix to address this. In the meantime you can still run your command by removing the version from the gene identifiers in your expression file.

**Comment by nourelislam** [comment]
@susannasiebert Thanks for your response, kindly note that I did it before "removing the versions from gene id" but still doesn't work. On the other hands, I have tried the recommended software "stringtie" to add transcript expression values and it works fine, but when I use "gene" argument instead of "transcript" it fails.
and here is the error:
Traceback (most recent call last):
  File "/home/nourelislam/anaconda3/envs/ngs1/bin/vcf-expression-annotator", line 10, in <module>
    sys.exit(main())
  File "/home/nourelislam/anaconda3/envs/ngs1/lib/python3.6/site-packages/vcf_annotation_tools/vcf_expression_annotator.py", line 191, in main
    (df, id_column, expression_column) = parse_expression_file(args, vcf_reader, vcf_writer)
  File "/home/nourelislam/anaconda3/envs/ngs1/lib/python3.6/site-packages/vcf_annotation_tools/vcf_expression_annotator.py", line 62, in parse_expression_file
    df = pd.read_csv(args.expression_file, sep='\t')
  File "/home/nourelislam/anaconda3/envs/ngs1/lib/python3.6/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/nourelislam/anaconda3/envs/ngs1/lib/python3.6/site-packages/pandas/io/parsers.py", line 463, in _read
    data = parser.read(nrows)
  File "/home/nourelislam/anaconda3/envs/ngs1/lib/python3.6/site-packages/pandas/io/parsers.py", line 1154, in read
    ret = self._engine.read(nrows)
  File "/home/nourelislam/anaconda3/envs/ngs1/lib/python3.6/site-packages/pandas/io/parsers.py", line 2048, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 879, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 894, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 948, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 935, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2130, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 1 fields in line 3, saw 9

**Comment by susannasiebert** [comment]
Can you please share the modified TSV with the gene identifier version removed?

The error indicates to me that you expression TSV is malformed but without seeing the actual input files, I won't be able to confirm this. Please share your input data and the exact command you ran.

**Comment by nourelislam** [comment]
@susannasiebert here is the exact command:
vcf-expression-annotator ~/Documents/neoantigen/DNA_data/hcc1395.build135650880.exome.indels.ann.vcf gerald_C2DBEACXX_3_XS.gtf stringtie gene -s H_NJ-HCC1395-HCC1395_BL-Pindel --ignore-transcript-version

and here is the expression file while the vcf file the same as in the above msgs
[gerald_C2DBEACXX_3_XS.gtf.gz](https://github.com/griffithlab/VAtools/files/3586722/gerald_C2DBEACXX_3_XS.gtf.gz)

**Comment by nourelislam** [comment]
@susannasiebert kindly note that I've made a **very** small subset from the original TSV file just to reduce the running time of that trial with making sure that the included gene ids are matching with that of VCF file.

here is the small subset expression file:
[test.txt](https://github.com/griffithlab/VAtools/files/3586746/test.txt)

**Comment by susannasiebert** [comment]
I think the stringtie file is failing because of the two comment lines on the top of the file. We should handle that so I will add it to this pull request: #29. For the modified file, you have a space after the each gene id and before the tab that separates it from the next column. It can't find the match because it tries to compare it with the space included in the identifier. Removing those spaces will fix this problem.

**Comment by susannasiebert** [comment]
Digging into the code some more there isn't actually any bug with our file parsing. The problem with your stringtie file is that you are trying to run the transcript gtf file in gene mode. There is a different output tsv file with gene expression information. You need to run that when using the gene mode. It should have a header like this:
```
Gene ID	Gene Name	Reference	Strand	Start	End	Coverage	FPKM	TPM
```

**Comment by susannasiebert** [comment]
Version 4.0.0 implements a `--ignore-ensembl-id-version` that will ignore gene as well as transcript id versions. This supersedes the previous `--ignore-transcript-version` flag.

**Comment by dubayc2** [comment]
I have been using the --refseq option in VEP, and I get transcripts like 'NM_001305275.2' in my VCF which will not map to my expression_file, which has 'NM_001305275' . The --ignore-ensembl-id-version flag does not fix this. Is there a workaround?

**Comment by nourelislam** [comment]
Hi,
Which transcriptomic assembly software did you use?...If you use a custom one rather than the recommended by VCF-annotator, it will most probably cause this type of error!
