### ISSUE TITLE
vcf-readcount-annotator: variant base is not present in the bam-readcount entry 

### ISSUE THREAD

**Issue by ne1al** [griffithlab/VAtools#30]
Hi!
I have two separate vcf files for a **tumor** sample, one for indels and another for snvs. Both have been VEP annotated and decomposed. The **indels vcf** file has different variant callers:
VarscanSomatic, Strelka, Pindel, and GatkSomaticIndel. Both the reference and the RNA-Seq BAM files were indexed. 
On running the `vcf-readcount-annotator` for **indels.vcf**, I received this warning for all samples in the vcf file of indels for all types of variant callers used in the vcf for almost all sites of indels:
`Warning: variant base +T is not present in the bam-readcount entry for variant X 80457914. This might indicate that the bam-readcount file doesn't match the VCF.`

Please note that I ran `bam_readcount_helper.py` script for indels, it gives this warning for almost all sites
`Complex variant or MNP will be skipped: GL000205.1 119085 CAAA CAAAA`

I am afraid that will impact the reliability of the resultant vcf annotated with tumor RNA coverage for indels. Please help

**Comment by susannasiebert** [comment]
Please post the the vcf-readcount-annotator command you ran for your indels vcf as well as the input files (indels vcf and indels bam-readcount file).

**Comment by ne1al** [comment]
Thank you Susanna for your prompt response.
[hcc1395.exome.indels.ann.decompose.vcf.gz](https://github.com/griffithlab/VAtools/files/3609226/hcc1395.exome.indels.ann.decompose.vcf.gz)
[trial.indels_H_NJ-HCC1395-HCC1395-VarscanSomatic_bam_readcount_indel.tsv.gz](https://github.com/griffithlab/VAtools/files/3609268/trial.indels_H_NJ-HCC1395-HCC1395-VarscanSomatic_bam_readcount_indel.tsv.gz)

This is the command for one sample (H_NJ-HCC1395-HCC1395-VarscanSomatic) in the uploaded vcf file where I am trying to add tumor RNA coverage:
`vcf-readcount-annotator hcc1395.exome.indels.ann.decompose.vcf trial.indels_H_NJ-HCC1395-HCC1395-VarscanSomatic_bam_readcount_indel.tsv RNA -s H_NJ-HCC1395-HCC1395-VarscanSomatic -t indel -o hcc1395.exome.indels.annotated1.vcf`

**Comment by ne1al** [comment]
Hello @susannasiebert , any updates? Please advise. Thank you

**Comment by susannasiebert** [comment]
I apologize but I haven't had time to work on this yet. I will try to get to it sometime this week.

**Comment by susannasiebert** [comment]
I meant to also asked whether you used the 1.1.1 version of the `bam_readcount_helper.py` helper script. We recently made a new release that fixed a pretty substantial bug related to indels. If you were using the 1.1.0 version, I recommend rerunning with version 1.1.1 first to see if that changes your results.

Next, I would check the reads for the variant in question to see if they meet the mapping and base quality cutoffs that were used when running bam-readcount. bam-readcount will not output positions/indel alleles if they don't have any supporting reads meeting the mapping and base quality cutoffs. This is the most likely culprit. I didn't see anything obviously wrong with your files. The variant in question is not a complex variant or MNP so the warning message from the helper script is unrelated.

In regards to complex indels, bam-readcount does not support those variants. However, the vcf-readcount-annotator will simply skip those VCF entries and doesn't write any readcounts to them. Any readcount fields for those variants will remain the ones written by the original variant caller.

**Comment by ne1al** [comment]
Thank you Susanna for your response.
Yes, I have used the updated version (1.1.1) of the `bam-readcount-helper.py` for the above files and commands

**Comment by ne1al** [comment]
Hello @susannasiebert , any updates from your side?

**Comment by susannasiebert** [comment]
Please see my previous comment

> Next, I would check the reads for the variant in question to see if they meet the mapping and base quality cutoffs that were used when running bam-readcount. bam-readcount will not output positions/indel alleles if they don't have any supporting reads meeting the mapping and base quality cutoffs. This is the most likely culprit. I didn't see anything obviously wrong with your files. The variant in question is not a complex variant or MNP so the warning message from the helper script is unrelated.

Have you checked some of these positions to see if the reads meet the mapping and base quality cutoffs?

**Comment by susannasiebert** [comment]
Of note is that the full bam-readcount entry for this position looks like this:
```
X	80457914	A	0	=:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	A:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	C:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	G:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	T:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00	N:0:0.00:0.00:0.00:0:0:0.00:0.00:0.00:0:0.00:0.00:0.00
```
So the depth is 0 which supports to assumption that there are no supporting reads for this position (that meet the quality cutoffs).

**Comment by susannasiebert** [comment]
Since there hasn't been any more activity on this issue, I assume that my last replies have answered the question. Feel free to reopen this issue if there are any additional concerns.

**Comment by SirKuikka** [comment]
Hi,

I have the same issue. 

I have a VCF file from tumor-normal somatic variant calling of a WES sample, and I am trying to add the RNAseq readcount values (RAD/RDP/RAF ) using a BAM file from the corresponding tumor RNA-seq sample. The issue happens only for indels, but not SNPs.

If I set minimum base quality to zero, this doesn't solve the error.

Should I be concerned about this?

**Comment by susannasiebert** [comment]
@SirKuikka can you please post a few of the specific warnings you are concerned about? Are the variants in questions simple or complex indels? What do the bam-readcount entries for those positions look like?

**Comment by SirKuikka** [comment]
> @SirKuikka can you please post a few of the specific warnings you are concerned about? Are the variants in questions simple or complex indels? What do the bam-readcount entries for those positions look like?




In the VCF file the first variant is chr1-229342253-GC-G

**Comment by susannasiebert** [comment]
Given the bam-readcount input you posted, the vcf-readcount-annotator seems to be doing the right thing. There might be a problem with bam-readcount but I'm not sure. It could simple mean that there is no RNA support for these specific variants? Do you get this warning for all simple indel variants in your VCF? You could consider putting in a ticket on the bam-readcount GitHub repo for clarification.

**Comment by SirKuikka** [comment]
> Given the bam-readcount input you posted, the vcf-readcount-annotator seems to be doing the right thing. There might be a problem with bam-readcount but I'm not sure. It could simple mean that there is no RNA support for these specific variants? Do you get this warning for all simple indel variants in your VCF? You could consider putting in a ticket on the bam-readcount GitHub repo for clarification.

Ok, that could be the reason. Didn't think about that.  Thanks.
