### ISSUE TITLE
warn when pick flag is expected but not observed

### ISSUE THREAD

**Issue by zlskidmore** [griffithlab/VAtools#36]
I have encountered issues wherree VEP --flag_pick appears to be broken, it will not flag a mutation with pick if that mutation intersects with multiple gene/transcript features. It would be beneficial if vep-annotation-reporter warned when it encounters entries where a pick flag is expected but not seen. In these cases it appears to pick the last consequence item from the vcf

**Comment by susannasiebert** [comment]
As it turns out, the underlying issue was already resolved in some previous version but as of 5.1.0 we now also output a warning for variants where none of the transcripts were PICK'ed and all transcripts' values are written to the output.
