### ISSUE TITLE
Installation via pip requires version previous than 21 because of Python version

### ISSUE THREAD

**Issue by danilotat** [griffithlab/VAtools#55]
As stated in [documentation](https://vatools.readthedocs.io/en/latest/install.html), installation via conda suggests the usage of pip. This is not gonna working with pip version higher than 21

Here's the message provided by pip version (< 20.2)

`
DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.`

**Comment by susannasiebert** [comment]
Thank you for bringing this to our attention. VAtools can be installed in any Python environment 3.5 and above. I will update the documentation to reflect that.

**Comment by susannasiebert** [comment]
The documentation has been updated. I will close this issue but do feel free to reopen should you run into problems installing VAtools.
