### ISSUE TITLE
vcf-readcount-annotator

### ISSUE THREAD

**Issue by pjleo** [griffithlab/VAtools#56]
HI 
I've got  a problem with annotation in using the latest vatools version. Input and output are attached: the  test vcf is vep annotated and decomposed. 

and the The counts are obtained using 

docker run --rm -i -t --mount type=bind,source=/mnt/,target=/mnt/ --mount type=bind,source=/mnt/ATG/,target=/mnt/ATG/ mgibio/bam_readcount_helper-cwl:1.0.0 /usr/bin/python /usr/bin/bam_readcount_helper.py /mnt/test.decomp.vcf TUMOR /mnt//reference_material/human_g1k_v37_decoy.fasta /mnt/tumour.bam /mnt/

which makes TUMOR_bam_readcount_snv.tsv and TUMOR_bam_readcount_indel.tsv attached below...

error when using:  ( I have the lasted vatools as of today March 3 2022

docker run --rm -i -t --mount type=bind,source=/mnt/,target=/mnt/ --mount type=bind,source=/mnt/ATG/,target=/mnt/ATG/ griffithlab/vatools:latest vcf-readcount-annotator /mnt/test.decomp.vcf /mnt/TUMOR_bam_readcount_snv.tsv DNA -s TUMOR -t snv -o /mnt/ATG/research/users/leop/research/scratch2/Grants/Riccardo/pvactools/vcf2022/test.decomp.DNA.vcf
Traceback (most recent call last):
  File "/usr/local/bin/vcf-readcount-annotator", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/vatools/vcf_readcount_annotator.py", line 206, in main
    for entry in vcf_reader:
  File "/usr/local/lib/python3.6/dist-packages/vcfpy/reader.py", line 175, in __next__
    result = self.parser.parse_next_record()
  File "/usr/local/lib/python3.6/dist-packages/vcfpy/parser.py", line 802, in parse_next_record
    return self.parse_line(self._read_next_line())
  File "/usr/local/lib/python3.6/dist-packages/vcfpy/parser.py", line 793, in parse_line
    return self._record_parser.parse_line(line)
  File "/usr/local/lib/python3.6/dist-packages/vcfpy/parser.py", line 457, in parse_line
    info = self._parse_info(arr[7], len(alts))
  File "/usr/local/lib/python3.6/dist-packages/vcfpy/parser.py", line 535, in _parse_info
    result[key] = parse_field_value(self.header.get_info_field_info(key), True)
  File "/usr/local/lib/python3.6/dist-packages/vcfpy/parser.py", line 266, in parse_field_value
    return convert_field_value(field_info.type, value)
  File "/usr/local/lib/python3.6/dist-packages/vcfpy/parser.py", line 243, in convert_field_value
    if "%" in value:
TypeError: argument of type 'bool' is not iterable

[TUMOR_bam_readcounts.zip](https://github.com/griffithlab/VAtools/files/8175051/TUMOR_bam_readcounts.zip)
[test.decomp.vcfs.zip](https://github.com/griffithlab/VAtools/files/8175058/test.decomp.vcfs.zip)

Any ideas???

Thanks
Paul

**Comment by susannasiebert** [comment]
Hi Paul,

This appears to be a  problem with some of your VCF entries, specifically the `ORIGINAL_MUTECT_FILTER` INFO field. This INFO field is defined like this:
```
##INFO=<ID=ORIGINAL_MUTECT_FILTER,Number=1,Type=String,Description="Original MuTect FILTER string">
```
i.e., a String field with exactly one value. However some of your VCF variants look like this
```
1	1560892	.	C	A	.	PASS	BAFP=99;BAFP_NORMAL=9;ECNT=1;HCNT=36;MAD_LEFT_OFFSET=8.00;MAD_RIGHT_OFFSET=0.00;MAX_ED=.;MEDIAN_LEFT_OFFSET=12.00;MEDIAN_RIGHT_OFFSET=75.00;MIN_ED=.;NLOD=37.79;ORIGINAL_MUTECT_FILTER;TLOD=59.21;TLOD_FWD=23.42;TLOD_REV=35.80;TUMOR_SB_POWER_FWD=0.999;TUMOR_SB_POWER_REV=1.000;CSQ=A|intron_variant|MODIFIER|MIB2|ENSG00000197530|Transcript|ENST00000505820.2|protein_coding||7/19|ENST00000505820.2:c.1210-34C>A|||||||||1||HGNC|30577||||||MAGALRRGRALGSRPSGPTVSSRRSPQCPVAQEGLGARSRPRVAPRSLARCGPSSRLMGWKPSEARGQSQSFQASGLQPRSLKAARRATGRPDRSRAARPTMDPSAHRSRAAPPNMDPDPQAGVQVGMRVVRGVDWKWGQQDGGEGGVGTVVELGRHGSPSTPDRTVVVQWDQGTRTNYRAGYQGAHDLLLYDNAQIGVRHPNIICDCCKKHGLRGMRWKCRVCLDYDLCTQCYMHNKHELAHAFDRYETAHSRPVTLSPRQGLPRIPLRGIFQGAKVVRGPDWEWGSQDGGEGKPGRVVDIRGWDVETGRSVASVTWADGTTNVYRVGHKGKVDLKCVGEAAGGFYYKDHLPRLGKPAELQRRVSADSQPFQHGDKVKCLLDTDVLREMQEGHGGWNPRMAEFIGQTGTVHRITDRGDVRVQFNHETRWTFHPGALTKHHSFWVGDVVRVIGDLDTVKRLQAGHGEWTDDMAPALGRVGKVVKVFGDGNLRVAVAGQRWTFSPSCLVAYRPEEDANLDVAERARENKSSLSVALDKLRAQKSDPEHPGRLVVEVALGNAARALDLLRRRPEQVDTKNQGRTALQVAAYLGQVELIRLLLQARAGVDLPDDEGNTALHYAALGNQPEATRVLLSAGCRADAINSTQSTALHVAVQRGFLEVVRALCERGCDVNLPDAHSDTPLHSAISAGTGASGIVEVLTEVPNIDVTATNSQGFTLLHHASLKGHALAVRKILARARQLVDAKKEDGFTALHLAALNNHREVAQILIREGRCDVNVRNRKLQSPLHLAVQQAHVGLVPLLVDAGCSVNAEDEEGDTALHVALQRHQLLPLVADGAGGDPGPLQLLSRLQASGLPGSAELTVGAAVACFLALEGADVSYTNHRGRSPLDLAAEGRVLKALQGCAQRFRERQAGGGAAPGPRQTLGTPNTVTNLHVGAAPGPEAAECLVCSELALLVLFSPCQHRTVCEECARRMKKCIRCQVVVSKKLRPDGSEVASAAPAPGPPRQLVEELQSRYRQMEERITCPICIDSHIRLVFQCGHGACAPCGSALSACPICRQPIRDRIQIFV	GT:AD:AF:ALT_F1R2:ALT_F2R1:FOXOG:QSS:REF_F1R2:REF_F2R1	0/1:27,18:0.400:9:9:0.500:1099,657:14:13	0/0:127,0:0.00:0:0:.:5082,0:59:68
```
specifically, note how the `ORIGINAL_MUTECT_FILTER` is only `ORIGINAL_MUTECT_FILTER;`. This doesn't match the field definition. If it matched it would look like `ORIGINAL_MUTECT_FILTER=some_filter;`. I'm not sure what tool might be populating this field but I assume that variants like the above does not have a mutect filter set. In those cases this field should just be absent from the INFO fields.

**Comment by pjleo** [comment]
Dear Susan, 
Thanks so much! I could not see the problem to save myself. 
I replaced entries as you suggested and no problems.
Thanks again for getting back so quickly.
Cheers
Paul

FYI the entries were put in using a GATK walker. I think the error occurs when the filter is "." originally. So yes its a custom annotation that cased the problem

**Comment by susannasiebert** [comment]
You're welcome. I will be closing this ticket but do feel free to reopen should you run into any additional problems.
