### ISSUE TITLE
Support gene names as well as gene Ensembl IDs when using the `custom` option of the `vcf-expression-annotator`

### ISSUE THREAD

**Issue by PierreLaplante** [griffithlab/VAtools#61]
Hi, 
I'm using 

vcf-expression-annotator *.vcf.gz *_geneNAME_count_header.tsv custom gene --id-column gene_name --expression-column expression

to annotate gene expression on VEP annotated VCF files using :

./vep \
--input_file $f --output_file $VCF \
--format vcf --vcf --everything --terms SO \
--species mus_musculus \
--symbol \
--offline --fasta Mus_musculus.GRCm39.dna_rm.primary_assembly.fa --cache --merged  \
--plugin Frameshift --plugin Wildtype \
--verbose \

After running the vcf-expression-annotator I get the error message : 

WARNING:root:13124 of 13124 genes did not have an expression entry for their gene id.

which means it doesn't find any match between the symbols from the .vcf and .tsv.

I have read issue #28 and I have checked my .tsv for incorrect spacing and such, but it seems to be correct. 
I can also find match manually between the gene_name from .tsv and the gene annotation of the .vcf.

Here is one of my .tsv (as .txt) as an example.
[gene_count.txt](https://github.com/griffithlab/VAtools/files/11759952/gene_count.txt)

Do you have an idea of what could cause this problem?

Thank you very much.

**Comment by susannasiebert** [comment]
@PierreLaplante I'm sorry that you're running into this issue.  I think what is happening, that when using the `custom` option we expect the gene values to be Ensembl gene ENSG IDs instead of a gene names. I know that's not obvious from the documentation and is something I will put on our todo list to fix. As a workaround, you could try changing the headers in your TSV file to be `gene_name` and `abundance` and then use the `kallisto` option instead of `custom`.

**Comment by PierreLaplante** [comment]
Thank you very much, problem solved!

**Comment by susannasiebert** [comment]
Wonderful. I will keep this ticket open as a reminder to address the original issue.

**Comment by susannasiebert** [comment]
After deliberating on this issue, we decided to not support gene names in the custom annotator. The reason being that gene names are not necessarily unique, some have been changed over time, and some genes don't have a gene name. For these reason, only Ensembl gene IDs will be supported going forward.
