### ISSUE TITLE
which version is on pip?

### ISSUE THREAD

**Issue by complexgenome** [griffithlab/VAtools#65]
Hi there developers,

Which version number is installed when I install vatools using:

`pip install vatools`

https://vatools.readthedocs.io/en/latest/install.html

**Comment by susannasiebert** [comment]
`pip install vatools` should install the latest version, which is currently 5.0.1. You can check what the latest version [on the pypi release history page](https://pypi.org/project/vatools/#history). You can also check which version is currently installed by running `pip show vatools`.

**Comment by complexgenome** [comment]
Thanks for your reply. It helps.
