### ISSUE TITLE
ref-transcript-mismatch-reporter does not work

### ISSUE THREAD

**Issue by xmy1990** [griffithlab/VAtools#74]
hello,
With ref-transcript-mismatch-reporter (vatools 5.1.0) on my **test_vep.vcf** as below:

**ref-transcript-mismatch-reporter test_vep.vcf --filter hard --output-vcf test.vcf**

The error still existed, the variant is as below:
chr12   48238361        .       G       GCCTCAATGAGGAGCACTCCAAGCAGTACCGCTGCCTCTCCTTCCAGCC       .       clustered_events        AS_FilterStatus=SITE;AS_SB_TABLE=101,4|1,6;DP=118;ECNT=5;GERMQ=93;MBQ=37,34;MFRL=52,194;MMQ=60,60;MPOS=49;NALOD=1.48;NLOD=8.75;POPAF=6;TLOD=19.3;CSQ=CCTCAATGAGGAGCACTCCAAGCAGTACCGCTGCCTCTCCTTCCAGCC|stop_gained&protein_altering_variant|HIGH|VDR|7421|Transcript|NM_001364085.1|protein_coding|10/10||NM_001364085.1:c.1451_1452insGGCTGGAAGGAGAGGCAGCGGTACTGCTTGGAGTGCTCCTCATTGAGG|NP_001351014.1:p.Asn484delinsLysAlaGlyArgArgGlySerGlyThrAlaTrpSerAlaProHisTer|1611-1612|1451-1452|484|N/KAGRRGSGTAWSAPH*G|aac/aaGGCTGGAAGGAGAGGCAGCGGTACTGCTTGGAGTGCTCCTCATTGAGGc|||-1||EntrezGene|||rseq_mrna_nonmatch&rseq_5p_mismatch||||OK|||||||||||||||MEAMAASTSLPDPGDFDRNVPRICGVCGDRATGFHFNAMTCEGCKGFFRRSMKRKALFTCPFNGDCRITKDNRRHCQACRLKRCVDIGMMKEFILTDEEVQRKREMILKRKEEEALKDSLRPKLSEEQQRIIAILLDAHHKTYDPTYSDFCQFRPPVRVNDGGGSHPSRPNSRHTPSFSGDSSSSCSDHCITSSDMMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSIQKVIGFAKMIPGFRDLTSEDQIVLLKSSAIEVIMLRSNESFTMDDMSWTCGNQDYKYRVSDVTKAGHSLELIEPLIKFQVGLKKLNLHEEEHVLLMAICIVSPDRPGVQDAALIEAIQDRLSNTLQTYIRCRHPPPGSHLLYAKMIQKLADLRSLNEEHSKQYRCLSFQPECSMKLTPLVLEVFGNEISLGQPVAVPGWGCSSRATCQARGWRLLSSPPHPVWGSAPPLPPPLSTQPILSPVQPNPFPAGFSPVP        GT:AD:AF:DP:F1R2:F2R1:SB        0/0:29,0:0.0318:29:17,0:12,0:29,0,0,0    0/1:76,7:0.0936:83:57,1:19,0:72,4,1,6

It has not been filtered, please help.

Thanks!

**Comment by susannasiebert** [comment]
This issue should be fixed in version 5.1.1 of VAtools. This variant, and others like it, will now be filtered out. Please give it a try and let me know if you're still running into problems.

**Comment by xmy1990** [comment]
Thanks for the quick response. 
The variant had benn filtered out. I am very curious about **what makes this mutation special**, to the extent that it was not filtered out previously with old version VAtools..

Thanks!

**Comment by susannasiebert** [comment]
Previous versions were not handling annotations with a protein_coding consequence (as opposed to inframe_insertion, inframe_indel, missense_variant, etc) while pVACtools would try to process such variants.
